name: Scheduled Status Check

on:
  # Run every 15 minutes
  schedule:
    - cron: '*/15 * * * *'
  # Allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin google-cloud-firestore

      - name: Create credentials file from secret
    # Questo è il nuovo metodo, più sicuro per stringhe complesse
        env:
            FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
            echo "$FIREBASE_CREDENTIALS_JSON" > firebase-credentials.json

      - name: Run status checker script
        run: python3 status_checker.py